apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.odeMessenger.name }}
data:
  appsettings.Production.json: |
    {
      "Authentication": {
          "Authority": "{{ .Values.url.authSettings.authority }}",
          "Api": "{{ .Values.url.authSettings.api }}"
      },
      "Kafka": {
          "bootstrap": {
              "servers": "{{ .Values.kafka.server }}"
          },
          "ssl": {
            "ca": "{{.Values.kafka.ca}}",
            "certificate": "{{.Values.kafka.certificate}}"
          },
          "sasl": {
              "mechanism": "{{.Values.kafka.security.mechanism}}",
              "username": "{{ .Values.kafka.userName }}"
          },
          "security": {
              "protocol": "{{ .Values.kafka.security.protocol}}"
          },
          "groupId": "{{ .Values.odeMessenger.kafka.groupId }}"
      },
      "Services": {
          "Configuration": "{{ .Values.url.transportProtocol }}://{{ .Values.url.apiHost }}/{{ .Values.url.configurationPath }}"
      }
    }
---apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.odeMessenger.name }}
  labels:
    app: {{ .Values.odeMessenger.name }}
    chart: {{ .Values.odeMessenger.name }}
    release: {{ .Release.Name }}
  annotations:
 
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.odeMessenger.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.odeMessenger.name }}   
        release: {{ .Release.Name }}
      annotations:
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              release: {{ .Release.Name }}
      imagePullSecrets:
        - name: {{ .Values.secrets.imagePullSecret }}
      volumes:
        - name: config
          configMap:
            name: {{ .Values.odeMessenger.name }}
      containers:
        - name: {{ .Values.odeMessenger.name }}
          image: "{{ .Values.odeMessenger.imageRepository }}:{{ .Values.odeMessenger.imageTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: Kafka__sasl__password
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.kafka.userName }}
                  key: password
            - name: Authentication__ClientId
              valueFrom:
                secretKeyRef:
                  name: authentication
                  key: clientId
            - name: Authentication__ClientSecret
              valueFrom:
                secretKeyRef:
                  name: authentication
                  key: clientSecret
          volumeMounts:
            - name: config
              mountPath: /app/appsettings.Production.json
              subPath: appsettings.Production.json
              readOnly: true
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if .Values.odeMessenger.probes.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- end }}
          resources:
{{ toYaml .Values.odeMessenger.resources | indent 12 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.odeMessenger.name }}
  labels:
    app: {{ .Values.odeMessenger.name }}
    chart: {{ .Values.odeMessenger.name }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.odeMessenger.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.odeMessenger.name }}